# A conf/layer.conf configuration file with default definitions.

# Here is an explanation of the typical content of the layer configuration file:

# BBPATH: Adds the layer’s root directory to BitBake’s search path. Through the use of the BBPATH variable, BitBake locates class files (.bbclass), configuration files, and files that are included with include and require statements. For these cases, BitBake uses the first file that matches the name found in BBPATH. This is similar to the way the PATH variable is used for binaries. It is recommended, therefore, that you use unique class and configuration filenames in your custom layer.

# See the Locating Include Files section of the BitBake User Manual for more details on how files are included with BitBake.

# BBFILES: Defines the location for all recipes in the layer.
# BBFILE_COLLECTIONS: Establishes the current layer through a unique identifier that is used throughout the OpenEmbedded Build System to refer to the layer. In this example, the identifier “yoctobsp” is the representation for the container layer named “meta-yocto-bsp”.

# This name is used by other layers when specifying the layer dependencies via the LAYERDEPENDS variable.

# BBFILE_PATTERN: Expands immediately during parsing to provide the directory of the layer.
# BBFILE_PRIORITY: Establishes a priority to use for recipes in the layer when the OpenEmbedded Build System finds recipes of the same name in different layers.
# LAYERVERSION: Establishes a version number for the layer. You can use this version number to specify this exact version of the layer as a dependency when using the LAYERDEPENDS variable.
# LAYERDEPENDS: Lists all layers on which this layer depends (if any). It uses the layer names specified by the BBFILE_COLLECTIONS variable.
# LAYERSERIES_COMPAT: Lists the Yocto Project release codenames (in lowercase) this layer is compatible with. For example: “whinlatter”.

# This variable is a good way to indicate if a particular layer is current.